config/routes.rb
Rails::Application.routes.draw do

  namespace :big_cms do
    resources :cms_files
    resources :layouts
    resources :components
    resources :navigations
    resources :pages
    resources :content_managers
  
    resources :pages do
      resources :versions, :controller => :page_versions
    end
  end
  match "content_manager" => 'big_cms/content_managers#show', :id => "current", :as => :content_manager

end

app/controllers/big_cms/cms_files_controller.rb
class BigCms::CmsFilesController < BigCmsController
  unloadable
  
  before_filter :unimplemented_error, :except => [:new, :create, :show, :index, :destroy]
  #before_filter :require_user, :except => :show

  # TODO: 2011-03-18 <tony+bigcms@tonsytubblebine.com> -- Trying to fix plupload weirdness. This should go away ASAP.
#  protect_from_forgery :except => [:create] 
  skip_before_filter :verify_authenticity_token, :only => [:create]

  # GET /big_cms/cms_files
  # GET /big_cms/cms_files.xml
  def index
    @cms_files = current_cms.files.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cms_files }
    end
  end

  # GET /big_cms/cms_files/1
  # GET /big_cms/cms_files/1.xml
  def show
    @cms_file = current_cms.files.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cms_file }
    end
  end

  # GET /big_cms/cms_files/new
  # GET /big_cms/cms_files/new.xml
  def new
    @cms_file = current_cms.files.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cms_file }
    end
  end

  # GET /big_cms/cms_files/1/edit
  def edit
    @cms_file = current_cms.files.find(params[:id])
  end

  # POST /big_cms/cms_files
  # POST /big_cms/cms_files.xml
  # TODO: 2011-05-14 <tony@crowdvine.com> -- Because this will return either a cms_file or a page, it's not very restful.
  def create
    if params[:big_cms_cms_file]
      @cms_file = current_cms.files.new(params[:big_cms_cms_file]) 
    else
      @cms_file = current_cms.files.new()
      @cms_file.file = params[:file]
    end

    if md = @cms_file.file.filename.match(/(.+).(htm|html|css|js)$/i)
      @title = md[1]
      @content_type = md[2]
      @page = current_cms.pages.new(:title => @title, :content => @cms_file.file.read)
      @page.content_type = (@content_type == "htm") ? "html" : @content_type
    end
      
    respond_to do |format|
      if @page and @page.save
        autolink_this(@page)
        if @page.content_type.nil?
          autolink_all(@cms_file.file.filename, big_cms_page_path(@page))
        else
          autolink_all(@cms_file.file.filename, big_cms_page_path(@page, :format => @content_type))
        end
        format.html { redirect_to(@cms_file, :notice => 'File uploaded and converted to and editable page.') }
        format.xml  { render :xml => @page, :status => :created, :location => @page }
      elsif @cms_file.save
        autolink_all(@cms_file.file.filename, @cms_file.file.url)
        format.html { redirect_to(@cms_file, :notice => 'File was successfully created.') }
        format.xml  { render :xml => @cms_file, :status => :created, :location => @cms_file }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cms_file.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /big_cms/cms_files/1
  # PUT /big_cms/cms_files/1.xml
  def update
    @cms_file = current_cms.files.find(params[:id])

    respond_to do |format|
      if @cms_file.update_attributes(params[:big_cms_cms_file])
        format.html { redirect_to(@cms_file, :notice => 'File was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cms_file.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /big_cms/cms_files/1
  # DELETE /big_cms/cms_files/1.xml
  def destroy
    @cms_file = current_cms.files.find(params[:id])
    @cms_file.destroy

    respond_to do |format|
      format.html { redirect_to(big_cms_cms_files_url) }
      format.xml  { head :ok }
    end
  end

  protected

  # TODO: 2011-05-24 <tony+bigcms@tonystubblebine.com> -- This entire
  # autlinking approach has a huge potential for false positives that I think
  # could be mostly eliminated by simply tracking if content has been human
  # edited, and skipping it in that case. 
  def autolink(content, name, path)
      # TODO: 2011-05-16 <tony+bigcms@tonystubblebine.com> -- Needs to handle case and skip absolute links
      # TODO: 2011-05-17 <tony+bigcms@tonystubblebine.com> -- Using gsub rather than gsub! in order to force content_changed?, which ends up getting used in the page versioning.
      content.content = content.content.gsub(/(src\s*=\s*['"]|url\s*\(\s*['"]?|href\s*=\s*['"]) 
                            [^'"\s\)]* 
                            #{name} 
                            \s* (["')])/x,
                            "\\1#{path}\\2")
      content.save if content.content_changed?
  end

  def autolink_this(content)
    current_cms.pages.each do |page|
      if page.content_type.nil?
        autolink(content, page.title, big_cms_page_path(page))
      else
        autolink(content, page.title + "." + page.content_type, big_cms_page_path(page, :format => page.content_type))
      end
    end

    current_cms.files.each do |file|
     autolink(content, file.file_file_name, file.file.url)
    end
  end
    
  def autolink_all(name, path)
    (current_cms.pages + current_cms.components).each do |content|
      autolink(content, name, path)
    end
  end
end

app/controllers/big_cms/components_controller.rb
class BigCms::ComponentsController < BigCmsController
  unloadable

  before_filter :require_user
  before_filter :unimplemented_error

  # GET /big_cms/components
  # GET /big_cms/components.xml
  def index
    @components = current_cms.components.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @components }
    end
  end

  # GET /big_cms/components/1
  # GET /big_cms/components/1.xml
  def show
    @component = current_cms.components.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @component }
    end
  end

  # GET /big_cms/components/new
  # GET /big_cms/components/new.xml
  def new
    @component = current_cms.components.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @component }
    end
  end

  # GET /big_cms/components/1/edit
  def edit
    @component = current_cms.components.find(params[:id])
  end

  # POST /big_cms/components
  # POST /big_cms/components.xml
  def create
    @component = current_cms.components.new(params[:big_cms_component])

    respond_to do |format|
      if @component.save
        format.html { redirect_to(@component, :notice => 'Component was successfully created.') }
        format.xml  { render :xml => @component, :status => :created, :location => @component }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @component.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /big_cms/components/1
  # PUT /big_cms/components/1.xml
  def update
    @component = current_cms.components.find(params[:id])
    respond_to do |format|
      if @component.update_attributes(params[:big_cms_component])
        format.html { render :action => "edit" }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @component.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /big_cms/components/1
  # DELETE /big_cms/components/1.xml
  def destroy
    @component = current_cms.components.find(params[:id])
    @component.destroy

    respond_to do |format|
      format.html { redirect_to(big_cms_components_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/big_cms/content_managers_controller.rb
class BigCms::ContentManagersController < BigCmsController
  unloadable

  before_filter :require_user
  before_filter :unimplemented_error, :except => [:show, :edit, :update]

  # GET /big_cms/content_managers
  # GET /big_cms/content_managers.xml
  def index
    @content_managers = BigCms::ContentManager.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @content_managers }
    end
  end

  # GET /big_cms/content_managers/1
  # GET /big_cms/content_managers/1.xml
  def show
    if params[:id].eql?("current")
      @content_manager = current_cms
    else
      @content_manager = BigCms::ContentManager.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @content_manager }
    end
  end

  # GET /big_cms/content_managers/new
  # GET /big_cms/content_managers/new.xml
  def new
    @content_manager = BigCms::ContentManager.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @content_manager }
    end
  end

  # GET /big_cms/content_managers/1/edit
  def edit
    @content_manager = BigCms::ContentManager.find(params[:id])
  end

  # POST /big_cms/content_managers
  # POST /big_cms/content_managers.xml
  def create
    @content_manager = BigCms::ContentManager.new(params[:big_cms_content_manager])

    respond_to do |format|
      if @content_manager.save
        format.html { redirect_to(@content_manager, :notice => 'Content manager was successfully created.') }
        format.xml  { render :xml => @content_manager, :status => :created, :location => @content_manager }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @content_manager.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /big_cms/content_managers/1
  # PUT /big_cms/content_managers/1.xml
  def update
    @content_manager = BigCms::ContentManager.find(params[:id])

    respond_to do |format|
      if @content_manager.update_attributes(params[:big_cms_content_manager])
        format.html { redirect_to(@content_manager, :notice => 'Content manager was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @content_manager.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /big_cms/content_managers/1
  # DELETE /big_cms/content_managers/1.xml
  def destroy
    @content_manager = BigCms::ContentManager.find(params[:id])
    @content_manager.destroy

    respond_to do |format|
      format.html { redirect_to(big_cms_content_managers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/big_cms/layouts_controller.rb
class BigCms::LayoutsController < BigCmsController
  unloadable
  before_filter :require_user
  before_filter :unimplemented_error, :except => [:index, :new, :create]


  # GET /big_cms/layouts
  # GET /big_cms/layouts.xml
  def index
    @layouts = current_cms.layouts

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @layouts }
    end
  end

  # GET /big_cms/layouts/1
  # GET /big_cms/layouts/1.xml
  def show
    @layout = current_cms.layouts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @layout }
    end
  end

  # GET /big_cms/layouts/new
  # GET /big_cms/layouts/new.xml
  def new
    @layout = current_cms.layouts.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @layout }
    end
  end

  # GET /big_cms/layouts/1/edit
  def edit
    @layout = current_cms.layouts.find(params[:id])
  end

  # POST /big_cms/layouts
  # POST /big_cms/layouts.xml
  def create
    @layout = current_cms.layouts.new(params[:big_cms_layout])

    respond_to do |format|
      if @layout.save
        format.html { redirect_to(@layout, :notice => 'Layout was successfully created.') }
        format.xml  { render :xml => @layout, :status => :created, :location => @layout }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @layout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /big_cms/layouts/1
  # PUT /big_cms/layouts/1.xml
  def update
    @layout = current_cms.layouts.find(params[:id])

    respond_to do |format|
      if @layout.update_attributes(params[:big_cms_layout])
        format.html { redirect_to(@layout, :notice => 'Layout was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @layout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /big_cms/layouts/1
  # DELETE /big_cms/layouts/1.xml
  def destroy
    @layout = current_cms.layouts.find(params[:id])
    @layout.destroy

    respond_to do |format|
      format.html { redirect_to(big_cms_layouts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/big_cms/page_versions_controller.rb
class BigCms::PageVersionsController < BigCmsController
  unloadable
  before_filter :set_page
  before_filter :require_user
  before_filter :unimplemented_error, :except => :create

  # GET /big_cms/pages/1/versions
  # GET /big_cms/pages/1/versions.xml
  def index
    @versions = @page.versions

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @versions }
    end
  end

  # GET /big_cms/pages/1/versions/1
  # GET /big_cms/pages/1/versions/1.xml
  def show
    @version = @page.versions.find_by_version(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @version }
    end
  end

  # GET /big_cms/pages/1/versions/new
  # GET /big_cms/pages/1/versions/new.xml
  def new
    @version = @page.versions.new

    respond_to do |format|a
      format.html # new.html.erb
      format.xml  { render :xml => @version }
    end
  end

  # GET /big_cms/pages/1/versions/1/edit
  def edit
    @version = @page.versions.find_by_version(params[:id])
  end

  # POST /big_cms/pages/1/versions?revert_to=1
  # POST /big_cms/page/1/versions.xml?revert_to=1
  def create
    @version = @page.versions.find_by_version(params[:revert_to])

    respond_to do |format|
      if @page.revert!(@version)
        format.html { redirect_to(edit_big_cms_page_path(@page), :notice => 'Reverted to version ##{@version.version}') }
        format.xml  { render :xml => @version.page, :status => :created, :location => @version.page }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @version.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /big_cms/pages/versions/1
  # PUT /big_cms/pages/versions/1.xml
  def update
    @version = @page.versions.find_by_version(params[:id])

    respond_to do |format|
      if @version.update_attributes(params[:big_cms_page_version])
        format.html { redirect_to(@version, :notice => 'Page version was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @version.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /big_cms/pages/1/versions/1
  # DELETE /big_cms/pages/1/versions/1.xml
  def destroy
    @version = @page.versions.find_by_version(params[:id])
    @version.destroy

    respond_to do |format|
      format.html { redirect_to(big_cms_page_versions_url) }
      format.xml  { head :ok }
    end
  end

  protected
  
  def set_page
    @page = current_cms.pages.find(params[:page_id])
  end
end

app/controllers/big_cms_controller.rb
class BigCmsController < ApplicationController
  protected

  # TODO: 2011-01-01 <tony@crowdvine.com> -- Two things here. One, isn't that
  # check supposed to be == "test." Two, can this be moved into a shared library
  # that all the big_* engines use?
  def unimplemented_error
    # Turn off things that aren't ready for production use, but still allow the tests to poke at them.
    unless ENV["RAILS_ENV"]
      render(:status => 404, :text => "This page does not exist.")
    end
  end
end

app/helpers/big_cms/layouts_helper.rb
module BigCms::LayoutsHelper
end

app/helpers/big_cms/page_versions_helper.rb
module BigCms::PageVersionsHelper
end

app/helpers/big_cms_helper.rb
module BigCmsHelper
  def foo(a="b")
    "foobar"
  end
 
  def snippet(name, *args)
    controller = @context.registers["controller"]
    component = controller.current_cms.components.find_by_name(name)
    opts = {"snippet" => component} 
    opts["current_site"] = controller.current_site if controller.current_site
    opts["current_layout"] = controller.current_layout if controller.current_layout
    opts["current_user"] = controller.current_user if controller.current_user
    opts["current_navigation"] = controller.current_cms.navigations if controller.current_cms


    args.each_with_index do |arg, i|
      opts["param#{(i+1).to_s}"] = arg
    end

    template = Liquid::Template.parse(component.content)
    template.render(opts, :filters => BigCms.service_configs[:liquid].filters, :registers => {"controller" => controller}).html_safe
  end

  def navigation_selected(slug)
    controller = @context.registers["controller"]
    if slug_nav = controller.current_cms.all_navigations.find{|a| a.slug == slug}
      if current_nav = controller.current_cms.all_navigations.find{|a| a.url == controller.request.path }
         return "selected" if slug_nav.ancestors_and_self.include?(current_nav)
      end
    end
    "" 
  end 
end

app/helpers/cms_files_helper.rb
module CmsFilesHelper
end

app/views/big_cms/cms_files/_admin_nav_listing.html.erb
<li class="cms_files">
  <a class="show_hide" href="#"></a> <%= link_to "Files", big_cms_cms_files_path(),  :class=>"folder-icon" %>
</li>
  <ul class="sub-contents">
	<li class="new"><%= link_to "Upload File(s)", new_big_cms_cms_file_path(), :class => "upload" %></li>
    <% current_cms.files.order(:file_file_name).each do |file| %>
      <li class="insert"><%= link_to file.file_file_name, file.file.url %></li>
    <% end %>
  </ul>

app/views/big_cms/cms_files/_form.html.erb
<%= form_for(@cms_file, :html => {:multipart => true}) do |f| %>
  <% if @cms_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cms_file.errors.count, "error") %> prohibited this file from being saved:</h2>

      <ul>
      <% @cms_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_file_name %><br />
    <%= image_tag(@cms_file.file.thumb.url) if @cms_file.file? %>
    <%= f.file_field :file %>
    <%= f.hidden_field :file_cache %>
  </div>
  <div class="actions">
    <%= f.submit "upload" %>
  </div>
<% end %>

app/views/big_cms/cms_files/edit.html.erb
<h1>Editing cms_file</h1>

<%= render 'form' %>

app/views/big_cms/cms_files/index.html.erb
<h1>Files</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Created At</th>
    <th></th>
  </tr>

<% @cms_files.each do |cms_file| %>
  <tr>
    <td><%= link_to(cms_file.file_file_name, cms_file.file.url) %></td>
    <td><%= cms_file.file.size %></td>
    <td><%= cms_file.created_at %></td>
    <td class="actions">
      <%= link_to "show", big_cms_cms_file_path(cms_file) %>
      <%= link_to "edit", edit_big_cms_cms_file_path(cms_file) %>
      <%= link_to 'delete', big_cms_cms_file_path(cms_file), :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/big_cms/cms_files/new.html.erb
<% content_for :big_cms_head do %>
<!-- Load Queue widget CSS and jQuery -->
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/base/jquery-ui.css" %> 
<%= stylesheet_link_tag "jquery.ui.plupload.css" %> 

<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js" %>
<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js" %>

<!-- Thirdparty intialization scripts, needed for the Google Gears and BrowserPlus runtimes -->
<%= javascript_include_tag "plupload/gears_init.js" %>
<%= javascript_include_tag "http://bp.yahooapis.com/2.4.21/browserplus-min.js" %>

<%= javascript_include_tag "plupload/plupload.full.min.js" %>
<%= javascript_include_tag "plupload/jquery.ui.plupload.min.js" %>
<!--<script type="text/javascript" src="http://getfirebug.com/releases/lite/1.2/firebug-lite-compressed.js"></script>-->

<script type="text/javascript">

// Convert divs to queue widgets when the DOM is ready

$(function() {

	// magic code: https://github.com/moxiecode/plupload/issues/275 - fixes issue in Chromium.

	if (!window.BlobBuilder && window.WebKitBlobBuilder)
	    window.BlobBuilder = window.WebKitBlobBuilder;

    $("#uploader").plupload({
        // General settings
        runtimes : 'html5,browserplus,silverlight,gears,html4',
        max_file_size : '10mb',  
        url : "/big_cms/cms_files",  
        flash_swf_url: "/javascripts/plupload/plupload.flash.swf",  
        silverlight_xap_url: "/javascripts/plupload/plupload.silverlight.xap",  
        multipart: true,  
        multipart_params: {  
          "authenticity_token" : '<%= form_authenticity_token %>'  
        },
        max_file_count: 20, // user can add no more then 20 files at a time
        // Rename files by clicking on their titles
        rename: true,
        // Sort files
        sortable: true
    });


    // Client side form validation
    $('form').submit(function(e) {
        var uploader = $('#uploader').plupload('getUploader');
        // Validate number of uploaded files
        if (uploader.total.uploaded == 0) {
            // Files in queue upload them first
            if (uploader.files.length > 0) {
                // When all files are uploaded submit form
                uploader.bind('UploadProgress', function() {
                    if (uploader.total.uploaded == uploader.files.length)
                        $('form').submit();
                });
                uploader.start();
            } else
                alert('You must at least upload one file.');
            e.preventDefault();
        }
    });
});

</script>
<% end %>

<h1>Upload Files</h1>

<%# render "form" %>

<form>
	<div id="uploader-wrapper">
		<div id="uploader">
  			<p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
		</div>
	</div>
</form>

app/views/big_cms/cms_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @cms_file.image? %>
    <%= image_tag @cms_file.file.url %><br />
  <% end %>
  <b>File file name:</b>
  <%= @cms_file.file_file_name %>
</p>

<p>
  <b>File content type:</b>
  <%= @cms_file.file_content_type %>
</p>

<p>
  <b>File file size:</b>
  <%= @cms_file.file_file_size %>
</p>

<p>
  <b>File updated at:</b>
  <%= @cms_file.file_updated_at %>
</p>