config/routes.rb
Rails::Application.routes.draw do

  namespace :big_cms do
    resources :cms_files
    resources :layouts
    resources :components
    resources :navigations
    resources :pages
    resources :content_managers
  
    resources :pages do
      resources :versions, :controller => :page_versions
    end
  end
  match "content_manager" => 'big_cms/content_managers#show', :id => "current", :as => :content_manager

end

app/models/big_cms/layout.rb
class BigCms::Layout < ActiveRecord::Base
  belongs_to :content_manager
end

app/controllers/big_cms/layouts_controller.rb
class BigCms::LayoutsController < BigCmsController
  unloadable
  before_filter :require_user
  before_filter :unimplemented_error, :except => [:index, :new, :create]


  # GET /big_cms/layouts
  # GET /big_cms/layouts.xml
  def index
    @layouts = current_cms.layouts

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @layouts }
    end
  end

  # GET /big_cms/layouts/1
  # GET /big_cms/layouts/1.xml
  def show
    @layout = current_cms.layouts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @layout }
    end
  end

  # GET /big_cms/layouts/new
  # GET /big_cms/layouts/new.xml
  def new
    @layout = current_cms.layouts.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @layout }
    end
  end

  # GET /big_cms/layouts/1/edit
  def edit
    @layout = current_cms.layouts.find(params[:id])
  end

  # POST /big_cms/layouts
  # POST /big_cms/layouts.xml
  def create
    @layout = current_cms.layouts.new(params[:big_cms_layout])

    respond_to do |format|
      if @layout.save
        format.html { redirect_to(@layout, :notice => 'Layout was successfully created.') }
        format.xml  { render :xml => @layout, :status => :created, :location => @layout }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @layout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /big_cms/layouts/1
  # PUT /big_cms/layouts/1.xml
  def update
    @layout = current_cms.layouts.find(params[:id])

    respond_to do |format|
      if @layout.update_attributes(params[:big_cms_layout])
        format.html { redirect_to(@layout, :notice => 'Layout was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @layout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /big_cms/layouts/1
  # DELETE /big_cms/layouts/1.xml
  def destroy
    @layout = current_cms.layouts.find(params[:id])
    @layout.destroy

    respond_to do |format|
      format.html { redirect_to(big_cms_layouts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/big_cms/layouts_helper.rb
module BigCms::LayoutsHelper
end

app/views/layouts/_big_admin_header.erb
<h1>Content Manager</h1>

app/views/layouts/_big_admin_nav_listing.html.erb
<div id="nav_listing">
    <ul id="main_nav">
    	<%= render "big_cms/layouts/admin_nav_listing"%>
        <%= render "big_cms/pages/admin_nav_listing" %>
        <%= render "big_cms/components/admin_nav_listing"%>
        <%= render "big_cms/cms_files/admin_nav_listing" %>
	</ul>
</div><!-- #nav_listing -->

app/views/layouts/_big_cms.html.erb
<%= stylesheet_link_tag "big_cms_admin" %>
<%= stylesheet_link_tag "http://jquery-ui.googlecode.com/svn/tags/1.8.11/themes/base/jquery.ui.resizable.css" %> 

<style>
    #body table {
      width: 100%;
    }
    #body td {
      text-align: center;
      vertical-align: middle;
    }
    #body tr.odd {
      background-color: #eee;
    }
    #content input[type="text"] {
      width: 300px;
    }
</style>

<script>
// embarassingly taken from about.com: http://javascript.about.com/library/blscreen2.htm
function pageHeight() {
 return  window.innerHeight != null? window.innerHeight : document.documentElement && document.documentElement.clientHeight ?  document.documentElement.clientHeight : document.body != null? document.body.clientHeight : null;} 

function setSizes() {
    $('#editor').height(pageHeight() - $('#editor').position().top - 46);
	$('#editor').width($('body').innerWidth() - $('#editor').position().left);
    $('.ace_scroller').width($('#editor').width() - 65);
	$('.ace_content').width($('.ace_scroller').width());
    $('#nav-resize').height($(window).height() - 54);
    $('#nav_listing').height($("#nav-resize").height() - 24);
    $('#nav').height($('#nav_listing').height() - 2);
    $('#nav .sub-contents li a').not('.insertCode, #upload').width($("#nav").width() - 90);
}

function setVisualSizes() {
	$(".wysiwyg, .wysiwyg iframe").width($('body').innerWidth() - $('.wysiwyg').position().left);
	$(".wysiwyg, .wysiwyg iframe").height((pageHeight() - $('.wysiwyg').position().top - 46));
}

</script> 
<% if !(controller.controller_name == "cms_files" and controller.action_name == "new") %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js" %>

  <%= javascript_include_tag 'big_lib_rails' %>
  <%= javascript_include_tag 'jquery.cookie' %>
  <%= javascript_include_tag 'ace/ace' %>
  <%= javascript_include_tag 'ace/mode-html' %>
  <%= javascript_include_tag 'ace/theme-twilight' %>
  <%= javascript_include_tag 'jquery.event.drag-2.0.min.js'%>
  <%= javascript_include_tag 'jquery.hotkeys'%>
  <%= stylesheet_link_tag "jquery.wysiwyg.css" %>
  <%= javascript_include_tag 'jquery.wysiwyg.js' %>
  <%= javascript_include_tag 'wysiwyg.link.js' %>
<script>
function findMainTextArea() {
  return $('#big_cms_page_content, #big_cms_layout_content, #big_cms_component_content');
}
function syncAceEditor() {
  var textarea = findMainTextArea();
  textarea[0].value = window.editor.getSession().getValue();
}

function syncVisualEditor() {
	var visualContent = findMainTextArea().wysiwyg("getContent");
	visualContent = new String(visualContent);
	window.editor.getSession().setValue(visualContent);
}

function setSourceCookie () {
	if($.cookie("visual-editor") === "true"){
		$.cookie("visual-editor", "false");
	}
	$.cookie("source-editor", "true", {expires: 25200000});
	$("#editor-mode #set-visual-mode-button").removeClass("active");
	$("#editor-mode #set-source-mode-button").addClass("active");
}


function setVisualCookie () {
	if($.cookie("source-editor") === "true"){
		$.cookie("source-editor", "false");
	}
	$.cookie("visual-editor", "true", {expires: 25200000});
	$("#editor-mode #set-source-mode-button").removeClass("active");
	$("#editor-mode #set-visual-mode-button").addClass("active");
}

function setActiveTab() {
	var current_url = String(window.location);
		if (current_url[1] === "source" || $.cookie("source-editor") === "true") {
			$("#editor-mode #set-visual-mode-button").removeClass("active");
			$("#editor-mode #set-source-mode-button").addClass("active");
		}
		
		else {
			$("#editor-mode #set-source-mode-button").removeClass("active");
			$("#editor-mode #set-visual-mode-button").addClass("active");
		}
		
}


function loadInNewSourceEditor () {
	var textarea = findMainTextArea();
	if (textarea.size() > 0) {
		textarea.after('<div id="editor" style="display:none;"></div>');
	    var editor = $('#editor');
	    textarea.hide();
	    editor.append(textarea.html());
	    editor.show();
	    setSizes();
	    var ace_editor = ace.edit("editor");
	    ace_editor.setTheme("ace/theme/twilight");
	    ace_editor.gotoLine(1);
	    var HTMLMode = require("ace/mode/html").Mode;
	    ace_editor.getSession().setMode(new HTMLMode());
	    ace_editor.renderer.setShowPrintMargin(false);
	    window.editor = ace_editor;
		setSizes();
	}
	setSourceCookie();
}


window.onload = function() {
	var current_url = String(window.location);
	var checkIfPage = current_url;
	checkIfPage = checkIfPage.split("/");
	current_url = current_url.split("#");
	
	if (checkIfPage[4] != "pages" && checkIfPage[checkIfPage.length - 1] != "content_manager") {
		if (current_url[1] === undefined) {
			if($.cookie("source-editor") === "true"){
				loadInNewSourceEditor();
				setSourceCookie();
			}
			
			if($.cookie("visual-editor") === "true"){
				setVisualCookie();
				loadInNewSourceEditor();
				setVisualCookie();
				setVisualMode();
				setVisualSizes();
			}
		}

		else if (current_url[1] === "source") {
			loadInNewSourceEditor();
			setSourceCookie();
			setActiveTab();
		}

		else {
			setVisualCookie();
			loadInNewSourceEditor();
			setVisualCookie();
			setVisualMode();
			setVisualSizes();
			setActiveTab();
		}
	}
	
	else if (checkIfPage[checkIfPage.length - 1] === "content_manager" || checkIfPage[checkIfPage.length - 1] === "roles_users"){
		$('#nav-resize').height($(window).height() - 54);
	}
	
	else {loadInNewSourceEditor();}
	

    $( "#nav" ).resizable({
        resize: function(event, ui) {
		setSizes();
        
        // still need to use these so the sidebar stays the same width upon refreshes.
        $.cookie("nav-width", $("#nav").width());
        $.cookie("editor-width", $("#editor").width());
      }
    });

    
    setTimeout(function() {
        if ($.cookie($(".pages .show_hide").next().text()) == "false"){
            $(".pages .show_hide").trigger("click");
        }
        
        if ($.cookie($(".components .show_hide").next().text()) == "false"){
            $(".components .show_hide").trigger("click");
        }
        
        if ($.cookie($(".cms_files .show_hide").next().text()) == "false"){
            $(".cms_files .show_hide").trigger("click");
        }
    
    },0);
    

  $('form.edit_big_cms_layout, form.edit_big_cms_page, form.edit_big_cms_component, form.new_big_cms_layout, form.new_big_cms_page, form.new_big_cms_component').submit(function() { 
    syncAceEditor();
  });

 $(".pages").next().find('li.edit a').each(function () {
    var page_id;
    if (page_id = $(this).attr("href").match(/pages\/(.+?)\/edit/) ) {
      var name = $(this).html();
      var insert = $('<a href="#" class="insertCode" title="Insert into editor"></a>')
      insert.click(function() {insertPage(page_id[1], name)})
      $(this).after(insert);
    };
  });

    $(".current-site").click(function() {
            $("#sites-dropdown").slideDown('fast').show(); 
            $("#sites-dropdown").hover(function() {
            }, function(){
                $("#sites-dropdown").slideUp('fast');
            });
        });

    $("#sites-dropdown li").click(function() {
        var url = $(this).find('span.under').text();
        url = "http://" + url + "/";
		window.open(url, '_blank');
    })

    $(".components").next().find('li.edit a').each(function () {
        var name = $(this).html();
        var insert = $('<a href="#" class="insertCode" title="Insert into editor"></a>')
        insert.click(function() {insertSnippet(name)})
        $(this).after(insert);
      });

    $(".cms_files").next().find('li.insert a').each(function () {
        var href = $(this).attr("href");
        var name = $(this).html();
        var insert = $('<a href="#" class="insertCode" title="Insert into editor"></a>')
        insert.click(function() {insertFile(href, name)})
        $(this).after(insert);
      });

	$("#update-page").click(function() {
		$("#ajax-icon").css("visibility", "visible");
	})


$("#main_nav > li").not('.folder-icon').click(function(){
    $(this).next().toggle();
    if ($(this).find(':first-child').hasClass('active-show_hide')){
        $.cookie($(this).find(':first-child').next().text(), "true");
        $(this).find(':first-child').removeClass('active-show_hide');
    }
    else{
        $.cookie($(this).find(':first-child').next().text(), "false");
        $(this).find(':first-child').addClass('active-show_hide');
    }
});

  $('#set-visual-mode-button').click(function(){
	var current_url = String(window.location);
	current_url = current_url.split("#");
	if (current_url[1] === "visual" || current_url[1] === "") {
		return false;
	}
	
	else {
		setVisualMode();
		setVisualSizes();	
	}
	
	setActiveTab();
  });

  $('#set-source-mode-button').click(function(){
	var current_url = String(window.location);
	current_url = current_url.split("#");
	if (current_url[1] === "source" || current_url[1] === "") {
		return false;
	}
	
	else {
		setSourceMode();
		setSizes();
	}
	setActiveTab();
  });

  setSizes();
  var checkIfPage = String(window.location);
  checkIfPage = checkIfPage.split("/");


  if(checkIfPage[checkIfPage.length - 1] === "new"){
	var checkIfPageContent = String("<!-- Insert a title in the box above, and put the rest of your content down here -->");
	window.editor.getSession().setValue(checkIfPageContent);
  }


  $("#new_big_cms_component, #new_big_cms_page, .edit_big_cms_page, .edit_big_cms_component").submit(function(){
	if ($("#big_cms_page_title, #big_cms_component_name").val() === ""){
		$("#ajax-icon").hide();
		alert("Please fill in a title to create this.");
		return false;
	}
	
	else if ($("#editor").text() === "1"){
		$("#ajax-icon").hide();
		alert("Please fill in content to create this.");
		return false;	
	}
	
	else{return true;}

  });


};

$(window).resize(function() {
	
    if ((window.location.toString().split("#")[1]) === "source" || $.cookie("source-editor") === "true") {
		setSizes();				
	}
	else {
		setVisualSizes();
	}
});


function insertSnippet(name) {
  window.editor.insert('{{ "' + name + '" | snippet }}');
}

function insertFile(url, name) {
    window.editor.insert(url);
}

function insertPage(id, name) {
  window.editor.insert("/pages/" + id);
}

function setVisualMode() {
  setVisualCookie();
  $('#editor').hide();
  syncAceEditor();
  findMainTextArea().show().wysiwyg(); 
}

function setSourceMode() {
  setSourceCookie();
  syncVisualEditor()
  findMainTextArea().wysiwyg("destroy");
  findMainTextArea().hide();
  $('#editor').show();

}
</script>
<% end %>

<%
    def link_to_with_highlight(name, options = {}, html_options = {})
      html_options.merge!({ :class => 'active' }) if current_page?(options)
      link_to(name, options, html_options)
    end
%>
  <div id="body">
    <div id="header">
        <%= render "layouts/big_admin_header" %>
    </div>
    <div id="nav">
      <%= render "layouts/big_admin_nav_listing" %>
    </div><!-- #nav -->
    <div id="nav-resize"></div>

    <div id="content">
      <%= yield %>
    </div>
    <div class="clear" />
  </div><!-- #body -->
<!-- need to insert a footer -->

app/views/layouts/big_cms.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yak</title>
  <%= stylesheet_link_tag "big_cms_admin" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js" %>
  <%= javascript_include_tag 'big_lib_rails' %>
  <%= javascript_include_tag 'ace/ace' %>
  <%= javascript_include_tag 'ace/mode-html' %>
 <script>
// This is based on the ACE bookmarklet.
function inject() { 
  var baseUrl="/javascripts/ace/"; 
  function load(path, module, callback) { 
    path = baseUrl + path; 
    if (!load.scripts[path]) { 
      load.scripts[path] = { loaded: false, callbacks: [ callback ] }; 
      var head = document.getElementsByTagName('head')[0]; 
      var s = document.createElement('script'); 
      function c() { 
        if (window.__ace_shadowed__ && window.__ace_shadowed__.define.modules[module]) { 
          load.scripts[path].loaded = true; 
          load.scripts[path].callbacks.forEach(function(callback) { callback(); }); 
        } else { setTimeout(c, 50); } 
      }; 
      s.src = path; 
      head.appendChild(s); 
      c(); 
    } else if (load.scripts[path].loaded) { 
      callback(); 
    } else { 
      load.scripts[path].callbacks.push(callback); 
    } 
  }; 
  load.scripts = {}; 
  window.__ace_shadowed_load__ = load; 
  if ((area = document.getElementById("big_cms_page_content")) || (area = document.getElementById("big_cms_layout_content")) || (area = document.getElementById("big_cms_component_content"))) {
    var ace = window.__ace_shadowed__; 
    var result = ace.transformTextarea(area); 
    result.setOption("mode", "html");
    result.setOption("gutter", true);
  }
};
</script> 
  <%= csrf_meta_tag %>
  <style>
    #body table {
      width: 100%;
    }
    #body td {
      text-align: center;
      vertical-align: middle;
    }
    #body tr.odd {
      background-color: #ccc;
    }
    #nav {
      float: left;
      width: 260px;
      padding-right: 20px;
    }
    #content {
      padding-left: 20px;
      padding-right: 20px;
      margin-left: 280px;
    }
    #content textarea {
      width: 100%;
    }
    #content input[type="text"] {
      width: 300px;
    }
  </style>
</head>
<body id="<%= controller.controller_name %>" class="<%= controller.action_name %>">
  <div id="body">
    <div id="nav">
      <h2>Content Management</h2>
      <ul id="main_nav">
        <li class="pages">
          <h3>Pages</h3>
          <ul>
            <li class="index"><%= link_to "Pages", big_cms_pages_path() %></li>
            <li class="new"><%= link_to "Add New", new_big_cms_page_path() %></li>
          </ul>
        </li>
        <li class="components">
          <h3>Snippets</h3>
          <ul>
            <li class="index"><%= link_to "Snippets", big_cms_components_path() %></li>
            <li class="new"><%= link_to "Add New", new_big_cms_component_path() %></li>
          </ul>
        </li>
        <li class="cms_files">
          <h3>Files</h3>
          <ul>
            <li class="index"><%= link_to "Files", big_cms_cms_files_path() %></li>
            <li class="new"><%= link_to "Upload", new_big_cms_cms_file_path() %></li>
          </ul>
        </li>
        <% if !(current_cms.layouts.nil? or current_cms.layouts.empty?) %>
          <li class="layouts">
            <h3>Layout</h3>
            <ul>
              <li class="new"><%= link_to "Web Layout", edit_big_cms_layout_path(current_cms.layouts.first) %></li>
            </ul>
          </li>
        <% end %>
        <li class="content_managers">
          <h3>Configuration</h3>
          <ul>
            <li class="edit"><%= link_to "Permissions", edit_big_cms_content_manager_path(current_cms) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- #nav -->

    <div id="content">
      <%= yield %>
    </div>
    <div class="clear" />
  </div><!-- #body -->
<script>
inject();
</script>
</body>
</html>